version: '3'

services:
  db:
    image: postgres:14
    networks:
      - back-modulejs
    expose:
      - 5432
    volumes:
      - 
    env_file:
      - ./.env
    restart: on-failure


  back:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: back-modulejs
    networks:
      - back-modulejs
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    restart: on-failure

networks:
  back-modulejs: