version: '3.3'

services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - 'postgres-volume/:/var/lib/postgresql/data'
    env_file:
      - ./.env.development
    restart: on-failure

volumes:
  postgres-volume: